# Generated by Django 4.2 on 2023-04-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interlock',
            new_name='InterlockInfo',
        ),
        migrations.RenameModel(
            old_name='LogParam',
            new_name='paramLog',
        ),
        migrations.RenameModel(
            old_name='LogRecipe',
            new_name='recipeLog',
        ),
        migrations.RenameField(
            model_name='recipelog',
            old_name='param_id',
            new_name='recipe_id',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='equipmentinfo',
            table='equipment_info',
        ),
        migrations.AlterModelTable(
            name='interlockinfo',
            table='interlock_info',
        ),
        migrations.AlterModelTable(
            name='loginterlock',
            table='interlock_log',
        ),
        migrations.AlterModelTable(
            name='lotinfo',
            table='lot_info',
        ),
        migrations.AlterModelTable(
            name='param',
            table='param',
        ),
        migrations.AlterModelTable(
            name='paramlog',
            table='param_log',
        ),
        migrations.AlterModelTable(
            name='qualityinfo',
            table='quality_info',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipelog',
            table='recipe_log',
        ),
    ]
