# ./Dockerfile
FROM python:3.8

RUN mkdir /fdc_server
ADD . /fdc_server
WORKDIR /fdc_server

## Install package
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Run the application on the port 8080
EXPOSE 8000 5432

# 배포 명령어
CMD ["python3", "manage.py",  "runserver", "0.0.0.0:8000"]