# ./Dockerfile
FROM python:3.8
WORKDIR /app

## Install package
COPY requirement.txt ./
RUN pip install -r requirement.txt

# Run the application on the port 8080
EXPOSE 8000

# 배포 명령어
RUN ["runserver"]